name: Node.js CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x.x]

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run lint
      # - run: yarn run test
      # - run: yarn build
        env:
          CI: true
